/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.administrador;

import davidpuertocuenca.autotech.controladores.AdministradorControlador;

/**
 *
 * @author David Puerto Cuenca
 */
public class VistaTalleresAdministrador extends javax.swing.JFrame {
    private AdministradorControlador controlador = new AdministradorControlador();
    /**
     * Creates new form VistaTalleresAdministrador
     */
    public VistaTalleresAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador.crearTablaTalleres(tablaTalleres, this);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organizadorVista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTalleres = new javax.swing.JTable();
        labelGestionarClientes = new javax.swing.JLabel();
        CabeceraVehiculos = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTalleres = new javax.swing.JMenu();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        JMenuItemAnadirTaller = new javax.swing.JMenuItem();
        JMenuItemModificarTaller = new javax.swing.JMenuItem();
        JMenuItemEliminarTaller = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        JMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMenuItemCitas = new javax.swing.JMenuItem();
        jMenuVehiculos = new javax.swing.JMenu();
        JMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoTech - Administrador");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizadorVista.setBackground(new java.awt.Color(255, 255, 255));
        organizadorVista.setForeground(new java.awt.Color(255, 255, 255));
        organizadorVista.setLayout(null);

        tablaTalleres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Número De Taller", "Nombre", "Dirección", "Código Postal", "Teléfono", "Localidad", "Identificación Fiscal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaTalleres.setToolTipText("");
        jScrollPane1.setViewportView(tablaTalleres);

        organizadorVista.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 1250, 530);

        labelGestionarClientes.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        labelGestionarClientes.setText("Gestión De Talleres");
        labelGestionarClientes.setToolTipText("");
        organizadorVista.add(labelGestionarClientes);
        labelGestionarClientes.setBounds(20, 10, 599, 70);

        CabeceraVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cliente/cabecera_vehiculos_prov.jpg"))); // NOI18N
        organizadorVista.add(CabeceraVehiculos);
        CabeceraVehiculos.setBounds(10, 10, 1250, 66);

        getContentPane().add(organizadorVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32768));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuTalleres.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTalleres.setText("Talleres");
        jMenuTalleres.setToolTipText("");
        jMenuTalleres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuTalleres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuTalleres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuTalleres.setMinimumSize(new java.awt.Dimension(50, 22));
        jMenuTalleres.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEmpleados.setText("Empleados");
        jMenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadosActionPerformed(evt);
            }
        });
        jMenuTalleres.add(jMenuItemEmpleados);

        JMenuItemAnadirTaller.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemAnadirTaller.setText("Añadir");
        JMenuItemAnadirTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemAnadirTallerActionPerformed(evt);
            }
        });
        jMenuTalleres.add(JMenuItemAnadirTaller);

        JMenuItemModificarTaller.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemModificarTaller.setText("Modificar");
        JMenuItemModificarTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemModificarTallerActionPerformed(evt);
            }
        });
        jMenuTalleres.add(JMenuItemModificarTaller);

        JMenuItemEliminarTaller.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemEliminarTaller.setText("Eliminar");
        JMenuItemEliminarTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemEliminarTallerActionPerformed(evt);
            }
        });
        jMenuTalleres.add(JMenuItemEliminarTaller);

        jMenuBar1.add(jMenuTalleres);

        jMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuUsuarios.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemUsuarios.setText("Menu De Usuarios");
        JMenuItemUsuarios.setToolTipText("");
        JMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(JMenuItemUsuarios);

        jMenuBar1.add(jMenuUsuarios);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Citas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemCitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemCitas.setText("Menu De Citas");
        JMenuItemCitas.setToolTipText("");
        JMenuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCitasActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItemCitas);

        jMenuBar1.add(jMenu3);

        jMenuVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        jMenuVehiculos.setText("Vehículos");
        jMenuVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuVehiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuVehiculos.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemVehiculos.setText("Menu De Vehículos");
        JMenuItemVehiculos.setToolTipText("");
        JMenuItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemVehiculosActionPerformed(evt);
            }
        });
        jMenuVehiculos.add(JMenuItemVehiculos);

        jMenuBar1.add(jMenuVehiculos);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemModificarTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemModificarTallerActionPerformed
        controlador.vistaModificarTaller(tablaTalleres, this);
    }//GEN-LAST:event_JMenuItemModificarTallerActionPerformed

    private void JMenuItemEliminarTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemEliminarTallerActionPerformed
       controlador.eliminarTaller(tablaTalleres, this);
    }//GEN-LAST:event_JMenuItemEliminarTallerActionPerformed

    private void JMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemUsuariosActionPerformed
        controlador.vistaUsuarios(this);
    }//GEN-LAST:event_JMenuItemUsuariosActionPerformed

    private void JMenuItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCitasActionPerformed
        controlador.vistaCitas(this);
    }//GEN-LAST:event_JMenuItemCitasActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        controlador.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void JMenuItemAnadirTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemAnadirTallerActionPerformed
        controlador.vistaAnadirTaller(this);
    }//GEN-LAST:event_JMenuItemAnadirTallerActionPerformed

    private void JMenuItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemVehiculosActionPerformed
        controlador.vistaVehiculos(this);
    }//GEN-LAST:event_JMenuItemVehiculosActionPerformed

    private void jMenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadosActionPerformed
        controlador.vistaEmpleados(this);
    }//GEN-LAST:event_jMenuItemEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaTalleresAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaTalleresAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaTalleresAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaTalleresAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaTalleresAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraVehiculos;
    private javax.swing.JMenuItem JMenuItemAnadirTaller;
    private javax.swing.JMenuItem JMenuItemCitas;
    private javax.swing.JMenuItem JMenuItemEliminarTaller;
    private javax.swing.JMenuItem JMenuItemModificarTaller;
    private javax.swing.JMenuItem JMenuItemUsuarios;
    private javax.swing.JMenuItem JMenuItemVehiculos;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenu jMenuTalleres;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JMenu jMenuVehiculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGestionarClientes;
    private javax.swing.JPanel organizadorVista;
    private javax.swing.JTable tablaTalleres;
    // End of variables declaration//GEN-END:variables
}
