/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.administrador;

import davidpuertocuenca.autotech.controladores.AdministradorControlador;

/**
 *
 * @author David Puerto Cuenca
 */
public class VistaEmpleadosTallerAdministrador extends javax.swing.JFrame {
    private AdministradorControlador controlador = new AdministradorControlador();
    /**
     * Creates new form VistaEmpleadosTallerAdministrador
     */
    public VistaEmpleadosTallerAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        controlador.crearTablaEmpleados(tablaEmpleados);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organizadorVista = new javax.swing.JPanel();
        labelGestionarClientes = new javax.swing.JLabel();
        CabeceraVehiculos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTalleres = new javax.swing.JMenu();
        jMenuItemAsignarTaller = new javax.swing.JMenuItem();
        jMenuItemEmpleados = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoTech - Administrador");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizadorVista.setBackground(new java.awt.Color(255, 255, 255));
        organizadorVista.setLayout(null);

        labelGestionarClientes.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        labelGestionarClientes.setText("Gestión De Empleados");
        labelGestionarClientes.setToolTipText("");
        organizadorVista.add(labelGestionarClientes);
        labelGestionarClientes.setBounds(20, 10, 520, 70);

        CabeceraVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cliente/cabecera_vehiculos_prov.jpg"))); // NOI18N
        organizadorVista.add(CabeceraVehiculos);
        CabeceraVehiculos.setBounds(10, 10, 1250, 66);

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dni", "Usuario", "Nombre", "Apellidos", "Taller Asignado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaEmpleados.setToolTipText("");
        tablaEmpleados.setMaximumSize(new java.awt.Dimension(1920, 1080));
        jScrollPane1.setViewportView(tablaEmpleados);

        organizadorVista.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 1250, 530);

        getContentPane().add(organizadorVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 670));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32768));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuTalleres.setForeground(new java.awt.Color(255, 255, 255));
        jMenuTalleres.setText("Talleres");
        jMenuTalleres.setToolTipText("");
        jMenuTalleres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuTalleres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuTalleres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuTalleres.setMinimumSize(new java.awt.Dimension(50, 22));
        jMenuTalleres.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemAsignarTaller.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemAsignarTaller.setText("Asignar Taller");
        jMenuItemAsignarTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignarTallerActionPerformed(evt);
            }
        });
        jMenuTalleres.add(jMenuItemAsignarTaller);

        jMenuItemEmpleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemEmpleados.setText("Volver a talleres");
        jMenuItemEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmpleadosActionPerformed(evt);
            }
        });
        jMenuTalleres.add(jMenuItemEmpleados);

        jMenuBar1.add(jMenuTalleres);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        controlador.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmpleadosActionPerformed
        controlador.vistaTalleres(this);
    }//GEN-LAST:event_jMenuItemEmpleadosActionPerformed

    private void jMenuItemAsignarTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignarTallerActionPerformed
        controlador.vistaAsignarTallerAEmpleado(tablaEmpleados, this);
    }//GEN-LAST:event_jMenuItemAsignarTallerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosTallerAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosTallerAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosTallerAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEmpleadosTallerAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEmpleadosTallerAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraVehiculos;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAsignarTaller;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemEmpleados;
    private javax.swing.JMenu jMenuTalleres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGestionarClientes;
    private javax.swing.JPanel organizadorVista;
    private javax.swing.JTable tablaEmpleados;
    // End of variables declaration//GEN-END:variables
}
