/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.administrador;

import davidpuertocuenca.autotech.controladores.AdministradorControlador;

/**
 *
 * 
 * @author David Puerto Cuenca
 */
public class VistaUsuariosAdministrador extends javax.swing.JFrame {
    private AdministradorControlador controlador = new AdministradorControlador();
        
    /**
     * Creates new form VistaGeneralAdministrador
     */
    public VistaUsuariosAdministrador() {
        initComponents();
        setExtendedState(VistaUsuariosAdministrador.MAXIMIZED_BOTH);

        controlador.crearTablaClientes(tablaUsuarios);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        botonRefrescar = new javax.swing.JButton();
        labelGestionarClientes = new javax.swing.JLabel();
        CabeceraClientes = new javax.swing.JLabel();
        fondoPantalla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        JMenuGestionClientes = new javax.swing.JMenu();
        JMenuItemAdministrador = new javax.swing.JMenuItem();
        jMenuQuitarAdministrador = new javax.swing.JMenuItem();
        JMenuItemModificarClientes = new javax.swing.JMenuItem();
        JMenuItemEliminarCliente = new javax.swing.JMenuItem();
        jMenuVehiculos = new javax.swing.JMenu();
        JMenuItemVehiculos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMenuItemCitas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMenuItemTalleres = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista General Administrador");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(1920, 1080));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Dni", "Nombre", "Apellidos", "Correo Electrónico", "Número De Teléfono", "Dirección", "Es Administrador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaUsuarios.setMaximumSize(new java.awt.Dimension(1300, 800));
        jScrollPane1.setViewportView(tablaUsuarios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1864;
        gridBagConstraints.ipady = 1110;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        botonRefrescar.setBackground(new java.awt.Color(255, 255, 255));
        botonRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icono_actualizar_prov .png"))); // NOI18N
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 120, 0, 0);
        getContentPane().add(botonRefrescar, gridBagConstraints);

        labelGestionarClientes.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        labelGestionarClientes.setText("Gestión De Usuarios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 1233;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        getContentPane().add(labelGestionarClientes, gridBagConstraints);

        CabeceraClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cliente/cabecera_vehiculos_prov.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = -66;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(CabeceraClientes, gridBagConstraints);

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_vistaGeneral_prov.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(fondoPantalla, gridBagConstraints);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32768));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setToolTipText("");
        jMenuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuUsuarios.setMinimumSize(new java.awt.Dimension(50, 22));
        jMenuUsuarios.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuGestionClientes.setText("Gestión");

        JMenuItemAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemAdministrador.setText("Hacer Administrador");
        JMenuItemAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemAdministradorActionPerformed(evt);
            }
        });
        JMenuGestionClientes.add(JMenuItemAdministrador);

        jMenuQuitarAdministrador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuQuitarAdministrador.setText("Quitar Administrador");
        jMenuQuitarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitarAdministradorActionPerformed(evt);
            }
        });
        JMenuGestionClientes.add(jMenuQuitarAdministrador);

        jMenuUsuarios.add(JMenuGestionClientes);
        JMenuGestionClientes.getAccessibleContext().setAccessibleName("Clientes");

        JMenuItemModificarClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemModificarClientes.setText("Modificar");
        JMenuItemModificarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemModificarClientesActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(JMenuItemModificarClientes);

        JMenuItemEliminarCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemEliminarCliente.setText("Eliminar");
        JMenuItemEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemEliminarClienteActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(JMenuItemEliminarCliente);

        jMenuBar1.add(jMenuUsuarios);

        jMenuVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        jMenuVehiculos.setText("Vehículos");
        jMenuVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuVehiculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuVehiculos.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemVehiculos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemVehiculos.setText("Menu De Vehículos");
        JMenuItemVehiculos.setToolTipText("");
        JMenuItemVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemVehiculosActionPerformed(evt);
            }
        });
        jMenuVehiculos.add(JMenuItemVehiculos);

        jMenuBar1.add(jMenuVehiculos);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Citas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemCitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemCitas.setText("Menu De Citas");
        JMenuItemCitas.setToolTipText("");
        JMenuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCitasActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItemCitas);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Talleres");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu4.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemTalleres.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemTalleres.setText("Menu De Talleres");
        JMenuItemTalleres.setToolTipText("");
        JMenuItemTalleres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemTalleresActionPerformed(evt);
            }
        });
        jMenu4.add(JMenuItemTalleres);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed
       controlador.crearTablaClientes(tablaUsuarios);
    }//GEN-LAST:event_botonRefrescarActionPerformed

    private void JMenuItemVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemVehiculosActionPerformed
        controlador.vistaVehiculos(this);
    }//GEN-LAST:event_JMenuItemVehiculosActionPerformed

    private void JMenuItemEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemEliminarClienteActionPerformed
        controlador.eliminarCliente(tablaUsuarios, this);
    }//GEN-LAST:event_JMenuItemEliminarClienteActionPerformed

    private void jMenuQuitarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitarAdministradorActionPerformed
        controlador.quitarAdministrador(tablaUsuarios, this);
    }//GEN-LAST:event_jMenuQuitarAdministradorActionPerformed

    private void JMenuItemAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemAdministradorActionPerformed
        controlador.hacerAdministrador(tablaUsuarios, this);
    }//GEN-LAST:event_JMenuItemAdministradorActionPerformed

    private void JMenuItemModificarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemModificarClientesActionPerformed
       controlador.vistaModificarUsuario(tablaUsuarios, this);
    }//GEN-LAST:event_JMenuItemModificarClientesActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        controlador.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void JMenuItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCitasActionPerformed
        controlador.vistaCitas(this);
    }//GEN-LAST:event_JMenuItemCitasActionPerformed

    private void JMenuItemTalleresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemTalleresActionPerformed
        controlador.vistaTalleres(this);
    }//GEN-LAST:event_JMenuItemTalleresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUsuariosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUsuariosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUsuariosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUsuariosAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUsuariosAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraClientes;
    private javax.swing.JMenu JMenuGestionClientes;
    private javax.swing.JMenuItem JMenuItemAdministrador;
    private javax.swing.JMenuItem JMenuItemCitas;
    private javax.swing.JMenuItem JMenuItemEliminarCliente;
    private javax.swing.JMenuItem JMenuItemModificarClientes;
    private javax.swing.JMenuItem JMenuItemTalleres;
    private javax.swing.JMenuItem JMenuItemVehiculos;
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuQuitarAdministrador;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JMenu jMenuVehiculos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelGestionarClientes;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
