/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.login;

import davidpuertocuenca.autotech.controladores.LoginControlador;
import static davidpuertocuenca.autotech.util.Estilos.aplicarEstiloBoton;
import static davidpuertocuenca.autotech.util.Estilos.aplicarEstiloPasswordField;
import static davidpuertocuenca.autotech.util.Estilos.aplicarEstiloTextField;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author David Puerto Cuenca
 */
public class LoginAdministradores extends javax.swing.JFrame {
    private LoginControlador controlador = new LoginControlador();
    /**
     * Creates new form LoginAdministradores
     */
    public LoginAdministradores() {
        initComponents();
        this.setLocationRelativeTo(null);
         //Estilos FrontEnd
        aplicarEstiloBoton(botonIniciarSesion);
        aplicarEstiloBoton(botonCancelar);
        aplicarEstiloTextField(textUsuario);
        aplicarEstiloPasswordField(textContrasena);
        
        //Método para acceder al programa pulsando enter.
        textContrasena.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               controlador.iniciarSesionAdministradores(textUsuario.getText(), textContrasena.getPassword(), LoginAdministradores.this);
            }
        });
        
        //Método para acceder al programa pulsando enter.
        textUsuario.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               controlador.iniciarSesionAdministradores(textUsuario.getText(), textContrasena.getPassword(), LoginAdministradores.this); 
            }
        });

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formularioLogin = new javax.swing.JPanel();
        textUsuario = new javax.swing.JTextField();
        botonMostrarContrasena = new javax.swing.JToggleButton();
        botonCancelar = new javax.swing.JButton();
        textContrasena = new javax.swing.JPasswordField();
        labelContrasena = new javax.swing.JLabel();
        labelUsuario1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        labelIniciarSesion = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JButton();
        fondoPantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AutoTech - Administrador");
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        formularioLogin.setBackground(new Color(20, 20, 20, 120));
        formularioLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textUsuario.setToolTipText("Usuario");
        formularioLogin.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 222, 42));

        botonMostrarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        botonMostrarContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/IconMostrarContrasena.png"))); // NOI18N
        botonMostrarContrasena.setBorder(null);
        botonMostrarContrasena.setContentAreaFilled(false);
        botonMostrarContrasena.setFocusPainted(false);
        botonMostrarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarContrasenaActionPerformed(evt);
            }
        });
        formularioLogin.add(botonMostrarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 40, 40));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        formularioLogin.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 100, 30));

        textContrasena.setToolTipText("Contraseña");
        formularioLogin.add(textContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 222, 42));

        labelContrasena.setForeground(new java.awt.Color(255, 255, 255));
        labelContrasena.setText("Contraseña");
        formularioLogin.add(labelContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));

        labelUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario1.setText("Usuario");
        formularioLogin.add(labelUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/logo.png"))); // NOI18N
        formularioLogin.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        labelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        labelIniciarSesion.setText("Iniciar Sesión");
        formularioLogin.add(labelIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 148, 40));

        botonIniciarSesion.setText("Login");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });
        formularioLogin.add(botonIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 100, 30));

        getContentPane().add(formularioLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 400, 470));
        formularioLogin.setBackground(new java.awt.Color(0, 0, 0, 120));

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_login.jpg"))); // NOI18N
        getContentPane().add(fondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        controlador.vistaClientes(this);
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonMostrarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarContrasenaActionPerformed
        if (textContrasena.getEchoChar() == '\u0000') {
            textContrasena.setEchoChar('•');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconMostrarContrasena.png")));
        } else {
            textContrasena.setEchoChar('\u0000');
            botonMostrarContrasena.setIcon(new ImageIcon(getClass().getResource("/icons/IconOcultarContrasena.png")));
        }
    }//GEN-LAST:event_botonMostrarContrasenaActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        controlador.iniciarSesionAdministradores(textUsuario.getText(), textContrasena.getPassword(), LoginAdministradores.this); 
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAdministradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JToggleButton botonMostrarContrasena;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JPanel formularioLogin;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelIniciarSesion;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField textContrasena;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
