/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.administrador.empleados;

import davidpuertocuenca.autotech.clases.Empleados;
import davidpuertocuenca.autotech.controladores.AdministradorControlador;

/**
 *
 * @author David Puerto Cuenca
 */
public class DialogAsignarTallerEmpleado extends javax.swing.JDialog {
    private AdministradorControlador controlador = new AdministradorControlador();
    private Empleados usuarioTaller;
    /**
     * Creates new form vistaAsignarTallerEmpleado
     */
    public DialogAsignarTallerEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public DialogAsignarTallerEmpleado(java.awt.Frame parent, boolean modal, Empleados usuarioTaller) {
        super(parent, modal);
        initComponents();
        this.usuarioTaller = usuarioTaller;
        this.setLocationRelativeTo(null);
        controlador.cargarTalleresUsuarioTallerComboBox(jComboBoxTallerAsignado, usuarioTaller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarEstado = new javax.swing.JPanel();
        jButtonCancelar = new javax.swing.JButton();
        jLabelTallerAsignado = new javax.swing.JLabel();
        jComboBoxTallerAsignado = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AutoTech - Administrador");
        setMaximumSize(new java.awt.Dimension(340, 220));
        setMinimumSize(new java.awt.Dimension(340, 220));
        setPreferredSize(new java.awt.Dimension(340, 220));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarEstado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        modificarEstado.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        jLabelTallerAsignado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTallerAsignado.setText("Taller Asignado:");
        modificarEstado.add(jLabelTallerAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        modificarEstado.add(jComboBoxTallerAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 214, 32));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        modificarEstado.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 30));

        getContentPane().add(modificarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 140));
        modificarEstado.setBackground(new java.awt.Color(0, 0, 0, 120));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_login.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        controlador.modificarTallerEmpleado(usuarioTaller, jComboBoxTallerAsignado, this);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarTallerEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarTallerEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarTallerEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAsignarTallerEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAsignarTallerEmpleado dialog = new DialogAsignarTallerEmpleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxTallerAsignado;
    private javax.swing.JLabel jLabelTallerAsignado;
    private javax.swing.JPanel modificarEstado;
    // End of variables declaration//GEN-END:variables
}
