/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.usuario;

import davidpuertocuenca.autotech.clases.Usuarios;
import davidpuertocuenca.autotech.controladores.UsuarioControlador;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JMenuBar;

/**
 *
 * @author David Puerto Cuenca
 */
public class VistaVehiculosUsuario extends javax.swing.JFrame {
    private Usuarios cliente;
    private UsuarioControlador controlador = new UsuarioControlador();
    /**
     * Creates new form VistaGeneralCliente
     */
    public VistaVehiculosUsuario() {
        initComponents();
        controlador.crearTablaVehiculos(tablaVehiculos, this.cliente);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }
    
    public VistaVehiculosUsuario(Usuarios cliente) {
        initComponents();
        this.cliente = cliente;
        controlador.crearTablaVehiculos(tablaVehiculos, this.cliente);
        controlador.colocarCerrarSesion(jMenuBar1, jMenu5); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        organizadorVista = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        labelVehiculos = new javax.swing.JLabel();
        CabeceraVehiculos = new javax.swing.JLabel();
        fondoPantalla = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        JMenuItemAnadirVehiculo = new javax.swing.JMenuItem();
        JMenuItemModificarVehiculo = new javax.swing.JMenuItem();
        JMenuItemEliminarVehiculo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMenuItemCitas = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mis Vehículos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        organizadorVista.setBackground(new java.awt.Color(255, 255, 255));
        organizadorVista.setLayout(null);

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Marca", "Modelo", "Año De Matriculación", "Color", "Citas Reservadas", "Número De Bastidor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVehiculos);

        organizadorVista.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 1250, 560);

        labelVehiculos.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        labelVehiculos.setText("Mis Vehículos");
        organizadorVista.add(labelVehiculos);
        labelVehiculos.setBounds(20, 0, 510, 80);

        CabeceraVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/cliente/cabecera_vehiculos_prov.jpg"))); // NOI18N
        organizadorVista.add(CabeceraVehiculos);
        CabeceraVehiculos.setBounds(10, 10, 1250, 66);

        getContentPane().add(organizadorVista);
        organizadorVista.setBounds(0, 0, 1270, 670);

        fondoPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_vistaGeneral_prov.jpg"))); // NOI18N
        getContentPane().add(fondoPantalla);
        fondoPantalla.setBounds(0, 0, 1920, 1030);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(90, 32768));
        jMenuBar1.setName(""); // NOI18N
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(50, 50));

        jMenuClientes.setForeground(new java.awt.Color(255, 255, 255));
        jMenuClientes.setText("Vehículos");
        jMenuClientes.setToolTipText("");
        jMenuClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuClientes.setMinimumSize(new java.awt.Dimension(50, 22));
        jMenuClientes.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemAnadirVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemAnadirVehiculo.setText("Añadir");
        JMenuItemAnadirVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemAnadirVehiculoActionPerformed(evt);
            }
        });
        jMenuClientes.add(JMenuItemAnadirVehiculo);

        JMenuItemModificarVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemModificarVehiculo.setText("Modificar");
        JMenuItemModificarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemModificarVehiculoActionPerformed(evt);
            }
        });
        jMenuClientes.add(JMenuItemModificarVehiculo);

        JMenuItemEliminarVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemEliminarVehiculo.setText("Eliminar");
        JMenuItemEliminarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemEliminarVehiculoActionPerformed(evt);
            }
        });
        jMenuClientes.add(JMenuItemEliminarVehiculo);

        jMenuBar1.add(jMenuClientes);

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Citas");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 40));

        JMenuItemCitas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemCitas.setText("Menu De Citas");
        JMenuItemCitas.setToolTipText("");
        JMenuItemCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCitasActionPerformed(evt);
            }
        });
        jMenu3.add(JMenuItemCitas);

        jMenuBar1.add(jMenu3);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setText("Cerrar Sesión");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 40));

        jMenuItemCerrarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItemCerrarSesion.setText("Cerrar Sesión");
        jMenuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void JMenuItemModificarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemModificarVehiculoActionPerformed
        controlador.vistaModificarVehiculo(tablaVehiculos, cliente, this);
    }//GEN-LAST:event_JMenuItemModificarVehiculoActionPerformed

    private void JMenuItemEliminarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemEliminarVehiculoActionPerformed
        controlador.eliminarVehiculo(tablaVehiculos, cliente, this);
    }//GEN-LAST:event_JMenuItemEliminarVehiculoActionPerformed

    private void JMenuItemCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCitasActionPerformed
        controlador.vistaCitas(tablaVehiculos, cliente, this);
    }//GEN-LAST:event_JMenuItemCitasActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        controlador.cerrarSesion(this);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void JMenuItemAnadirVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemAnadirVehiculoActionPerformed
       controlador.vistaAnadirVehiculo(this, cliente);
    }//GEN-LAST:event_JMenuItemAnadirVehiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaVehiculosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaVehiculosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CabeceraVehiculos;
    private javax.swing.JMenuItem JMenuItemAnadirVehiculo;
    private javax.swing.JMenuItem JMenuItemCitas;
    private javax.swing.JMenuItem JMenuItemEliminarVehiculo;
    private javax.swing.JMenuItem JMenuItemModificarVehiculo;
    private javax.swing.JLabel fondoPantalla;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelVehiculos;
    private javax.swing.JPanel organizadorVista;
    private javax.swing.JTable tablaVehiculos;
    // End of variables declaration//GEN-END:variables
}
