/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package davidpuertocuenca.autotech.vistas.administrador.citas;

import davidpuertocuenca.autotech.clases.Citas;
import davidpuertocuenca.autotech.controladores.AdministradorControlador;
/**
 *
 * @author David Puerto Cuenca
 */
public class DialogCambiarEstadoCitaAdministrador extends javax.swing.JDialog {
    private AdministradorControlador controlador = new AdministradorControlador();
    private Citas cita;
    /**
     * Creates new form dialogCambiarEstadoCita
     */
    public DialogCambiarEstadoCitaAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public DialogCambiarEstadoCitaAdministrador(java.awt.Frame parent, boolean modal, Citas cita) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.cita = cita;
                
        controlador.cargarEstadoCitaComboBox(jComboBoxEstadoCita, cita);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modificarEstado = new javax.swing.JPanel();
        jLabelEstadoCita = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxEstadoCita = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Estado Cita");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modificarEstado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEstadoCita.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstadoCita.setText("Estado de la cita.");
        modificarEstado.add(jLabelEstadoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 17, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        modificarEstado.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        modificarEstado.add(jComboBoxEstadoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 39, 220, 32));

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        modificarEstado.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, 30));

        getContentPane().add(modificarEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 140));
        modificarEstado.setBackground(new java.awt.Color(0, 0, 0, 120));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stiles/fondo_login.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
         controlador.modificarEstadoCita(cita, jComboBoxEstadoCita, this);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarEstadoCitaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarEstadoCitaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarEstadoCitaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCambiarEstadoCitaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCambiarEstadoCitaAdministrador dialog = new DialogCambiarEstadoCitaAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBoxEstadoCita;
    private javax.swing.JLabel jLabelEstadoCita;
    private javax.swing.JPanel modificarEstado;
    // End of variables declaration//GEN-END:variables
}
